// SVG component imports - mixing explicit static imports (for committed files)
// with import.meta.glob (for dynamically generated files by sync job).
// vite-plugin-svgr uses namedExport: 'ReactComponent', so use { ReactComponent as Name }.
// mol_hiking.svg, mol_cycling.svg, mol_swimming.svg, mol_skiing.svg are NOT in git
// and are only generated by the sync job.
import type { ComponentType } from 'react';

import { ReactComponent as Year2012Svg } from './year_2012.svg';
import { ReactComponent as Year2013Svg } from './year_2013.svg';
import { ReactComponent as Year2014Svg } from './year_2014.svg';
import { ReactComponent as Year2015Svg } from './year_2015.svg';
import { ReactComponent as Year2016Svg } from './year_2016.svg';
import { ReactComponent as Year2017Svg } from './year_2017.svg';
import { ReactComponent as Year2018Svg } from './year_2018.svg';
import { ReactComponent as Year2019Svg } from './year_2019.svg';
import { ReactComponent as Year2020Svg } from './year_2020.svg';
import { ReactComponent as Year2021Svg } from './year_2021.svg';
import { ReactComponent as Year2022Svg } from './year_2022.svg';
import { ReactComponent as Year2023Svg } from './year_2023.svg';
import { ReactComponent as Year2024Svg } from './year_2024.svg';
import { ReactComponent as Year2025Svg } from './year_2025.svg';
import { ReactComponent as Year2026Svg } from './year_2026.svg';

import { ReactComponent as YearSummary2012Svg } from './year_summary_2012.svg';
import { ReactComponent as YearSummary2013Svg } from './year_summary_2013.svg';
import { ReactComponent as YearSummary2014Svg } from './year_summary_2014.svg';
import { ReactComponent as YearSummary2015Svg } from './year_summary_2015.svg';
import { ReactComponent as YearSummary2016Svg } from './year_summary_2016.svg';
import { ReactComponent as YearSummary2017Svg } from './year_summary_2017.svg';
import { ReactComponent as YearSummary2018Svg } from './year_summary_2018.svg';
import { ReactComponent as YearSummary2019Svg } from './year_summary_2019.svg';
import { ReactComponent as YearSummary2020Svg } from './year_summary_2020.svg';
import { ReactComponent as YearSummary2021Svg } from './year_summary_2021.svg';
import { ReactComponent as YearSummary2022Svg } from './year_summary_2022.svg';
import { ReactComponent as YearSummary2023Svg } from './year_summary_2023.svg';
import { ReactComponent as YearSummary2024Svg } from './year_summary_2024.svg';
import { ReactComponent as YearSummary2025Svg } from './year_summary_2025.svg';
import { ReactComponent as YearSummary2026Svg } from './year_summary_2026.svg';

import { ReactComponent as Github2021Svg } from './github_2021.svg';
import { ReactComponent as Github2022Svg } from './github_2022.svg';
import { ReactComponent as Github2023Svg } from './github_2023.svg';
import { ReactComponent as Github2024Svg } from './github_2024.svg';
import { ReactComponent as Github2025Svg } from './github_2025.svg';
import { ReactComponent as Github2026Svg } from './github_2026.svg';

import { ReactComponent as GithubSvg } from './github.svg';
import { ReactComponent as GridSvg } from './grid.svg';
import { ReactComponent as MolSvg } from './mol.svg';
import { ReactComponent as MolRunningSvg } from './mol_running.svg';
import { ReactComponent as MolWalkingSvg } from './mol_walking.svg';

export const yearStats: Record<string, ComponentType<any>> = {
  './year_2012.svg': Year2012Svg,
  './year_2013.svg': Year2013Svg,
  './year_2014.svg': Year2014Svg,
  './year_2015.svg': Year2015Svg,
  './year_2016.svg': Year2016Svg,
  './year_2017.svg': Year2017Svg,
  './year_2018.svg': Year2018Svg,
  './year_2019.svg': Year2019Svg,
  './year_2020.svg': Year2020Svg,
  './year_2021.svg': Year2021Svg,
  './year_2022.svg': Year2022Svg,
  './year_2023.svg': Year2023Svg,
  './year_2024.svg': Year2024Svg,
  './year_2025.svg': Year2025Svg,
  './year_2026.svg': Year2026Svg,
};

export const yearSummaryStats: Record<string, ComponentType<any>> = {
  './year_summary_2012.svg': YearSummary2012Svg,
  './year_summary_2013.svg': YearSummary2013Svg,
  './year_summary_2014.svg': YearSummary2014Svg,
  './year_summary_2015.svg': YearSummary2015Svg,
  './year_summary_2016.svg': YearSummary2016Svg,
  './year_summary_2017.svg': YearSummary2017Svg,
  './year_summary_2018.svg': YearSummary2018Svg,
  './year_summary_2019.svg': YearSummary2019Svg,
  './year_summary_2020.svg': YearSummary2020Svg,
  './year_summary_2021.svg': YearSummary2021Svg,
  './year_summary_2022.svg': YearSummary2022Svg,
  './year_summary_2023.svg': YearSummary2023Svg,
  './year_summary_2024.svg': YearSummary2024Svg,
  './year_summary_2025.svg': YearSummary2025Svg,
  './year_summary_2026.svg': YearSummary2026Svg,
};

export const githubYearStats: Record<string, ComponentType<any>> = {
  './github_2021.svg': Github2021Svg,
  './github_2022.svg': Github2022Svg,
  './github_2023.svg': Github2023Svg,
  './github_2024.svg': Github2024Svg,
  './github_2025.svg': Github2025Svg,
  './github_2026.svg': Github2026Svg,
};

export const totalStat: Record<string, ComponentType<any>> = {
  './github.svg': GithubSvg,
  './grid.svg': GridSvg,
  './mol.svg': MolSvg,
  './mol_running.svg': MolRunningSvg,
  './mol_walking.svg': MolWalkingSvg,
  // mol_hiking, mol_cycling, mol_swimming, mol_skiing are generated by sync job
  // Use import.meta.glob with { import: 'ReactComponent' } to get named export
  ...((import.meta.glob('./mol_hiking.svg', { import: 'ReactComponent', eager: true }) as Record<string, ComponentType<any>>) || {}),
  ...((import.meta.glob('./mol_cycling.svg', { import: 'ReactComponent', eager: true }) as Record<string, ComponentType<any>>) || {}),
  ...((import.meta.glob('./mol_swimming.svg', { import: 'ReactComponent', eager: true }) as Record<string, ComponentType<any>>) || {}),
  ...((import.meta.glob('./mol_skiing.svg', { import: 'ReactComponent', eager: true }) as Record<string, ComponentType<any>>) || {}),
};
